sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

install:
  - sudo apt-get install libboost-all-dev

script:
  - make
  - ~/bin/demo
  - ~/bin/test.run

notifications:
  email: false
